---
# defaults file for k8scluster
# Directory to store the archive
containerd_config_directory: "/etc/containerd"

containerd_config_dest: "/etc/containerd/config.toml"
containerd_url: "https://gist.githubusercontent.com/oradwell/31ef858de3ca43addef68ff971f459c2/raw/5099df007eb717a11825c3890a0517892fa12dbf/containerd-config.toml"

# Directory to store the archive
containerd_tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}"

cd_url: "https://github.com/containerd/containerd/releases/download/v1.6.14/containerd-1.6.14-linux-amd64.tar.gz"

containerd_binary_directory: "/usr/local"

containerd_service_url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"

runc_download_url: "https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.amd64"
runc_install_dir: "/usr/local/sbin"

cni_url: "https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz"
cni_plugins_install_dir: "/opt/cni/bin"

cni_plugins_archive_name: "cni-plugins-linux-amd64-v1.1.1.tgz"